# Chromatin Differentiation in Dysfunctional T cells

In [1]:
# imports
from datascience import Table
%matplotlib inline
import numpy as np

All data in this lab comes from https://www.nature.com/articles/nature22367. This paper, titled 'Chromatin states define tumour-specific T cell dysfunction and reprogramming', collects ATAC-seq data from normal and dysfunctional T cells that were immunized with Listeria monoctgogenes strain. Here, we compare the accessibility between these two groups. Today, we will look at this datasets to draw similar conclusions regarding the change in epigenetic state of T cell dysfunction.

Data can be found at https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE89309.

First, load in the data.

In [2]:
table = Table.read_table('https://raw.githubusercontent.com/data-8/mcb-88-connector/gh-pages/data/lab4/dysfunctional_ATACseq_timeseries.csv')
table

chr  | start    | end      | symbol        | refseqID  | peak_annotation | N1      | N2      | N3      | E5_1    | E5_2    | E5_3    | E7_2    | E7_3    | M1      | M2      | M3      | L5_1    | L5_2    | L5_3    | L5_4    | L7_1    | L7_2    | L7_3    | L14_1   | L14_2   | L14_3   | L21_1   | L21_2   | L21_3   | L28_1   | L28_2   | L28_3   | L35_1   | L35_2   | L35_3   | L60_1   | L60_2   | L60_3
chr1 | 9772732  | 9773228  | 1700034P13Rik | NR_040462 | intergenic      | 209.153 | 221.576 | 241.935 | 129.291 | 148.714 | 132.882 | 150.143 | 189.593 | 255.555 | 270.364 | 236.631 | 113.379 | 113.803 | 123.402 | 128.035 | 113.542 | 145.413 | 153.614 | 125.268 | 124.401 | 145.569 | 205.532 | 221.787 | 193.068 | 243.36  | 145.573 | 197.799 | 167.201 | 180.65  | 159.028 | 147.345 | 180.696 | 166.505
chr1 | 9797805  | 9798616  | Sgk3          | NM_133220 | promoter        | 538.113 | 596.551 | 655.475 | 355.311 | 294.949 | 347.62  | 390.926 | 387.085 | 542.902 | 707.899 | 495.03  | 249.435 | 323.829 | 393.837 | 393.25  | 299.414 | 284.931 | 417.973 | 291.065 | 237.629 | 237.223 | 275.05  | 264.352 | 234.588 | 274.863 | 255.656 | 302.111 | 214.586 | 214.048 | 170.021 | 216.862 | 155.424 | 201.024
chr1 | 9859046  | 9859750  | Sgk3          | NM_133220 | intron          | 178.694 | 186.59  | 187.546 | 702.002 | 616.336 | 559.168 | 671.84  | 641.004 | 666.4   | 769.815 | 579.29  | 231.992 | 248.886 | 370.207 | 397.823 | 432.299 | 350.76  | 405.469 | 257.905 | 290.518 | 273.423 | 384.616 | 357.324 | 311.4   | 224.458 | 333.255 | 311.951 | 286.34  | 274.012 | 367.89  | 163.213 | 180.696 | 226.406
chr1 | 10089499 | 10089955 | Cspp1         | NM_026493 | intron          | 251.796 | 204.532 | 209.114 | 161.853 | 113.188 | 126.504 | 170.901 | 202.007 | 235.991 | 212.576 | 153.775 | 97.6808 | 111.027 | 110.274 | 121.938 | 117.747 | 114.955 | 162.545 | 127.11  | 108.013 | 179.458 | 161.705 | 210.586 | 167.118 | 191.38  | 141.362 | 184.022 | 150.955 | 193.554 | 201.533 | 148.101 | 190.805 | 191.887
chr1 | 12875425 | 12875883 | Slco5a1       | NM_172841 | intron          | 185.801 | 126.487 | 137.847 | 131.206 | 115.666 | 144.576 | 143.916 | 135.423 | 176.076 | 189.874 | 126.391 | 125.59  | 123.055 | 149.658 | 195.101 | 203.534 | 105.13  | 210.773 | 198.034 | 196.658 | 200.253 | 281.095 | 228.508 | 230.436 | 353.621 | 300.17  | 307.031 | 326.278 | 255.036 | 312.926 | 272.777 | 295.685 | 341.132
chr1 | 13293331 | 13293833 | Ncoa2         | NM_008678 | intron          | 305.607 | 357.93  | 292.572 | 203.035 | 280.904 | 248.755 | 282.989 | 226.834 | 289.792 | 251.789 | 415.685 | 172.686 | 222.979 | 212.672 | 285.03  | 264.089 | 211.242 | 235.78  | 183.297 | 265.936 | 284.206 | 315.854 | 262.112 | 290.64  | 367.009 | 259.866 | 274.557 | 373.663 | 335.494 | 375.218 | 334.738 | 341.175 | 342.148
chr1 | 20933432 | 20933875 | Paqr8         | NM_028829 | intron          | 480.24  | 470.961 | 512.94  | 267.201 | 195.806 | 223.242 | 208.263 | 273.104 | 326.475 | 375.62  | 339.148 | 176.174 | 271.091 | 241.553 | 233.207 | 237.176 | 280.018 | 344.738 | 227.509 | 188.464 | 250.317 | 247.847 | 250.911 | 247.044 | 215.795 | 192.494 | 224.369 | 200.37  | 239.096 | 244.771 | 173.036 | 245.14  | 222.345
chr1 | 23255935 | 23256632 | Mir30a        | NR_029533 | intergenic      | 681.271 | 940.128 | 810.201 | 398.408 | 372.61  | 407.151 | 455.965 | 457.054 | 627.272 | 1362.14 | 870.691 | 378.513 | 401.548 | 446.349 | 495.374 | 555.934 | 445.082 | 512.642 | 233.036 | 192.934 | 331.958 | 205.532 | 254.271 | 166.08  | 165.39  | 294.756 | 137.77  | 158.401 | 199.626 | 240.374 | 281.845 | 235.032 | 194.933
chr1 | 23762738 | 23763139 | B3gat2        | NM_172124 | promoter        | 102.546 | 82.5303 | 58.1394 | 168.557 | 125.58  | 143.513 | 152.219 | 168.151 | 397.394 | 400.386 | 193.097 | 231.992 | 215.577 | 216.61  | 184.431 | 300.255 | 199.452 | 185.766 | 136.321 | 113.228 | 106.288 | 144.326 | 153.459 | 107.952 | 129.162 | 153.393 | 130.882 | 111.693 | 165.47  | 168.555 | 151.879 | 236.295 | 138.077
chr1 | 33739113 | 33739764 | Rab23         | NM_008999 | exon            | 248.75  | 276.297 | 302.888 | 239.428 | 228.854 | 186.035 | 199.269 | 268.59  | 231.1   | 284.811 | 223.29  | 160.476 | 183.195 | 168.037 | 245.4   | 204.375 | 193.556 | 207.2   | 228.43  | 238.374 | 179.458 | 221.4   | 229.628 | 205.524 | 176.417 | 179.861 | 266.684 | 194.955 | 233.783 | 263.092 | 163.969 | 183.224 | 159.398
... (75679 rows omitted)

In this dataset, each peak has a location (chr, start and end) as well as an associated gene symbol. The peak annotation tells us where the peak occurs.

The rest of the dataset has labels N1, E5, E7, ... L60_3. These abbreviations stand for the following:

<h3>Normal T Cells</h3> 

- N1: Naive T cell
- E5: Effector cell after incubated for 5 days
- E7: Effector cell after incubated for 7 days
- M1: Memory cell

<h3>Dysfunctional T Cells</h3> 

- L5: Dysfunctional T cells after 5 days
- L7: Dysfunctional T cells after 7 days
- L14: Dysfunctional T cells after 14 days
- L21: Dysfunctional T cells after 21 days
- L28: Dysfunctional T cells after 28 days
- L35: Dysfunctional T cells after 35 days
- L60: Dysfunctional T cells after 60 days

You may notice there are multiple samples for each category (i.e. E5_1, E5_2, E5_3). These represent biological replicates.

<h2 style="color:red">** Question 1**</h2> 

How many ATAC-seq peaks does this dataset have?

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

---
## <span style="color:red">Student Answer</span>

*For the next question, double click on the text and add your answer below the question text*

---

<h2 style="color:red">** Question 2**</h2> 

Is there more or less ATAC-seq peaks in this dataset than you would expect in the same dataset for RNA-seq? Explain.

## Part 1: Exploring differential accessibility in normal T Cells

For part 1 of the lab, we will compare differentially accessible regions between different T cell activation states in normal T cells. To do this, we need a method that can calculate whether the diffence in accessibility at a given genomic region in two cell states is statistically significant. To determine whether sites are significantly different, we need a **differential peak calling** algorithm. These algorithms are able to determine which genes are significantly differentially accessible between two states (i.e. naive and effector). We will use our own peak calling algorithm to calculate differential peaks.

First, let us define a peak calling function called **callDifferentialPeaks()**:

In [7]:
def callDifferentialPeaks(table, CAT1_NAMES, CAT2_NAMES):
    '''
    Calls peaks on two categories of peak calling data. Can be used for ATAC-seq or RNA-seq.
    Borrowed from http://dept.stat.lsa.umich.edu/~kshedden/Python-Workshop/gene_expression_comparison.html

    param1: Table data: takes for from 
    https://raw.githubusercontent.com/data-8/mcb-88-connector/gh-pages/data/lab4/dysfunctional_ATACseq_timeseries.csv
    param1: column names of first category
    param2: column names of second category
    return: Table of differentially called regions
        Positive values mean the peak was siginificantly higher in the first category
        Negative values mean the peak was significantly higher in the second category
    '''

    # gene list
    GID = list(table.column('symbol'))

    # matrix of values
    dropped = table.drop(['chr', 'start', 'end', 'symbol','refseqID', 'peak_annotation'])
    X = np.array(dropped.to_df().as_matrix())
    # list of categories
    SID = list(table.column_labels)[6:]
    
    # get indices of category names
    CAT1 = [list(dropped.column_labels).index(i) for i in CAT1_NAMES]
    CAT2 = [list(dropped.column_labels).index(i) for i in CAT2_NAMES]
    

    ## Convert X to log scale
    XL = np.log(X) / np.log(2)

    M1 = XL[:,CAT1].mean(1) ## Mean of category 1 samples for each data point
    M2 = XL[:,CAT2].mean(1) ## Mean of category2 samples for each data point
    V1 = XL[:,CAT1].var(1)  ## Variance of category 1 samples for each data point
    V2 = XL[:,CAT2].var(1)  ## Variance of category 2 samples for each data point
    n1 = len(CAT1)          ## Number of category 1 samples
    n2 = len(CAT2)          ## Number of category 2 samples

    # calculate Z score
    Z = (M1 - M2) / np.sqrt(V1/n1 + V2/n2)

    ## Gaussian distribution CDF, pdf, quantile function, etc.
    from scipy.stats.distributions import norm

    ## The Z-score threshold under a Bonferroni correction
    zst = -norm.ppf(0.025/Z.shape[0])

    # indices of differentially expressed genes
    ii = np.flatnonzero(np.abs(Z) > zst) 
    scores = Z[ii] # scores
    genes = np.array(GID)[ii] # gene names
    annotation = np.array(table.column('peak_annotation'))[ii]
    chr = np.array(table.column('chr'))[ii]
    start = np.array(table.column('start'))[ii]
    end = np.array(table.column('end'))[ii]

    # create new table with differential regions
    newTable = Table().with_columns(['chr', chr, 'start', start, 'end', end,'peak_annotation', annotation, 'symbol', genes, 'score', scores])

    return newTable

This method takes as input the data table we are analyzing, as well as the column names of the first category and second category we would like to compare. For example, let's compare naive and 5 day effector states:

In [8]:
# get column names of category 1 and 2
CAT1_NAMES = ['N1','N2','N3'] 
CAT2_NAMES = ['E5_1','E5_2','E5_3']

calledPeaksN = callDifferentialPeaks(table, CAT1_NAMES, CAT2_NAMES)

calledPeaksN

/srv/app/venv/lib/python3.6/site-packages/datascience/tables.py:234: FutureWarning: column_labels is deprecated; use labels
  warnings.warn("column_labels is deprecated; use labels", FutureWarning)
/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:30: RuntimeWarning: divide by zero encountered in log
/srv/app/venv/lib/python3.6/site-packages/numpy/core/_methods.py:112: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:40: RuntimeWarning: invalid value encountered in subtract
/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:49: RuntimeWarning: invalid value encountered in greater

chr  | start    | end      | peak_annotation | symbol        | score
chr1 | 9772732  | 9773228  | intergenic      | 1700034P13Rik | 10.0271
chr1 | 9797805  | 9798616  | promoter        | Sgk3          | 8.74773
chr1 | 9859046  | 9859750  | intron          | Sgk3          | -22.0576
chr1 | 10089499 | 10089955 | intron          | Cspp1         | 5.03553
chr1 | 20933432 | 20933875 | intron          | Paqr8         | 9.99897
chr1 | 23255935 | 23256632 | intergenic      | Mir30a        | 9.06698
chr1 | 34867183 | 34867587 | intron          | Plekhb2       | 23.9799
chr1 | 35890111 | 35890946 | intergenic      | Hs6st1        | 8.13463
chr1 | 39478274 | 39479009 | promoter        | Tbc1d8        | 18.8915
chr1 | 40514972 | 40515601 | promoter        | Il18rap       | -16.9661
... (26291 rows omitted)

The score column contains how different the peak was between the two categories. Positive values indicate that the peak is more accessible in the first category (i.e. more accessible in naive). Negative values indicate that the peak is more accessible in the second category (i.e. more accessible in effector)

<h2 style="color:red">** Question 3**</h2> 

How many peaks in the table above are more accessible in 5 day effector cells, compared to naive cells?
How many peaks in the table above are less accessible in 5 day effector cells, compared to naive cells? (Save these values as variables, we will be plotting them later)

In [5]:
# YOUR CODE HERE
raise NotImplementedError()

NotImplementedError:

<h2 style="color:red">** Question 4**</h2> 

Find all of the differential peaks between the E5 to E7 (Effector 5 day and 7 day) cell states.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

<h2 style="color:red">** Question 5**</h2> 

How many peaks in the table above are more accessible in 7 day effector cells, compared to 5 day effector cells?
How many peaks in the table above are less accessible in 7 day effector cells, compared to 5 day effector cells? (Save these values as variables, we will be plotting them later)

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

<h2 style="color:red">** Question 6**</h2> 

Repeat this process to find the number of differentially accessible peaks for the transition from E7 to M.

How many peaks in the table above are more accessible in memory cells, compared to 7 day effector cells?
How many peaks in the table above are less accessible in memory cells, compared to 7 day effector cells? (Save these values as variables, we will be plotting them later)

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

<h2 style="color:red">** Question 7**</h2> 

Make a bar plot that shows shows these changes in accessibility for the transitions N->E5, E5->E7, and E7->M. Plot closed peaks as negative values for easier viewing. There should be 6 total bars on the plot. Make sure to label the axes. (Hint: To make this plot, you can make a new table with the values computed above. You can then use the **.bar()** function to plot a bar graph.) If you are unsure of what this plot may sort of look at, reference Figure 1B in the paper for help.

For some examples, try here: https://pythonspot.com/matplotlib-bar-chart/ 

For documentation on matplotlib's bar plot function: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.bar.html

In [6]:
# YOUR CODE HERE
import matplotlib.pyplot as plt
#plt.bar() will the function used to plot bar graphs

raise NotImplementedError()

NotImplementedError:

---
## <span style="color:red">Student Answer</span>

*For the next question, double click on the text and add your answer below the question text*

---

<h2 style="color:red">** Question 8**</h2> 

Given the bar chart above, which transition has the fewest differences in accessibily? Which transition has the most changes in accessibily?

Now, we will look at some of the genes and observe how their accessibility peaks change over T cell activation.

<h2 style="color:red">** Question 9**</h2> 

The first gene, Cd44, was stated in the paper to have low expression in naive cells. Filter the table of differentially expressed genes in the peak table called **calledPeaksN** that overlap Cd44. Do the scores reflect more or less accessibility in naive cells compared to 5 day effector cells?

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

## Part 2: Comparing Normal and Dysfunction T cell accessibility

Now, we will compare the normal effector states (E5/E7) to dysfunctional T cell states (L5/L7)

<h2 style="color:red">** Question 10**</h2> 

Run the differential peak calling algorithm, differentiating peaks between normal effector states (E5/E7) and dysfunctional T cell states (L5/L7). Print the resulting table. Hint: Think about the function we defined earlier and what it's inputs are.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

<h2 style="color:red">** Question 11**</h2> 

PD1 protein (encoded by Pdcd1 gene) is correlated with cell death. Look at the peaks around PD1 from the table above. Are the values associated with more or less accessibility in the normal states, compared to the dysfunctional states? Does this make sense, given the gene's function?

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

## Part 3: Viewing ATAC-seq data in UCSC Genome Browser

Now, we will view accessibility sites for activated T cells in the UCSC genome browser. 

1. Navigate to http://rstats.immgen.org/Chromatin/chromatin.html. 
2. Select ab T cells. Under the ab T cell category, select all of the NK (natural killer) cell categories. There are 4.
![UCSC Home Page](https://raw.githubusercontent.com/data-8/mcb-88-connector/gh-pages/images/lab4/select_NKcells.png)
    
3. Search for the gene 'Gzma' and click 'View data on UCSC Genome Browser'

---
## <span style="color:red">Student Answer</span>

*For the next question, double click on the text and add your answer below the question text*

---

<h2 style="color:red">** Question 12**</h2> 
Viewing Gzma in the genome browser, does the naive cell (NKT_Sp) look more or less accessible than the other three activated cell states?

<h2 style="color:red">** Question 13**</h2> 
Navigate to gene cards (http://www.genecards.org/) and search for the gene **Gzma** and read the description. What process is this gene involved in? Does the function of this gene align with the accessibility trends you observed in the previous question? Explain.

<h2 style="color:red">** Bonus Question**</h2> 
Describe, in your own words, how the differential peak calling algorithm works.